# -*- coding: utf-8 -*-
"""MAtplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gwd_3O0yD9QLQRzZICV0sSxAPdPKHcLm
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

price = [100, 200, 300, 400, 80, 190, 330000]
year=[2015, 2016, 2017, 2018, 2019, 2020, 2021]
plt.ylim(0,1000)
plt.grid()
plt.xlabel('Year')
plt.ylabel('Price')
plt.title('Price of Iphone')
plt.plot(year,price)
plt.show()

data=pd.read_csv('sharma-kohli.csv')
print(data)
plt.plot(data['index'],data['V Kohli'],color="red" ,label='Virat Kohli')
plt.plot(data['index'],data['RG Sharma'],color="Blue",label='Rohit Sharma')
plt.title("Comparson bitween Rohit Sharma and Virat Kohli")
plt.xlabel("Year")
plt.ylabel("Runs")
plt.legend()
plt.show()

from google.colab import drive
drive.mount('/content/drive')

batter=pd.read_csv('batter.csv')
top=batter.head(50)
# print(top)
plt.scatter(batter['avg'],batter['strike_rate'],marker='+',color="black")
plt.xlabel('Average')
plt.ylabel('Strike Rate')
plt.title('Average ans Strike rate analysis of top 50 batsman ')
plt.show()

"""#Bar **chart**"""

Children=[10, 25, 15, 30, 20] # Added sample data
color=['red','blue','green','yellow','pink']
plt.bar(color,Children)
plt.xlabel('Color') # Added x-axis label
plt.ylabel('Number of Children') # Added y-axis label
plt.title('Number of Children by Color') # Added title
plt.show()

"""#**Multiple Bar chart**"""

df=pd.read_csv('batsman_season_record.csv')
print(df)
plt.bar(df['batsman'],df['2015'])
plt.show()

import numpy as np

plt.bar(np.arange(df.shape[0]) - 0.2, df['2015'], width=0.2)
plt.bar(np.arange(df.shape[0]), df['2016'], width=0.2)
plt.bar(np.arange(df.shape[0]) + 0.2, df['2017'], width=0.2)

plt.xticks(np.arange(df.shape[0]), df['batsman'])
plt.xlabel('Batsman')
plt.ylabel('Runs')
plt.show()

arr=np.load('big-array.npy')
plt.hist(arr)
# plt.show()

"""#**Pie chart**"""

data=[23,45,100,20,15,9.5]
subject=['eng','science','maths','hindi','social','computer']
plt.pie(data,labels=subject)

data=pd.read_csv('/content/gayle-175.csv')
print(data)

plt.pie(data['batsman_runs'],labels=data['batsman'],autopct="%0.1f")
plt.show()

"""#save figure"""

plt.savefig("performance of batsman")

"""## **Advance Matplotlib**"""

iris=pd.read_csv('iris.csv')
iris.head()

plt.scatter(iris['SepalLengthCm'],iris['PetalLengthCm'])
plt.show()

iris['Species']=iris['Species'].replace({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})
iris

plt.scatter(iris['SepalLengthCm'],iris['PetalLengthCm'],c=iris['Species'])
plt.xlabel('SepalLengthCm')
plt.ylabel('PetalLengthCm')
plt.colorbar()
plt.show()

"""# **changing graph size**"""

plt.figure(figsize=(15,10)) #this is for size of figure

#lower code is decribe the figure
plt.scatter(iris['SepalLengthCm'],iris['PetalLengthCm'],c=iris['Species'])
plt.xlabel('SepalLengthCm')
plt.ylabel('PetalLengthCm')
plt.colorbar()

"""# **Annotation**"""

batters=pd.read_csv('batter.csv')

batters.shape

sample_df=batters.head(100).sample(25,random_state=5)

print(sample_df)

plt.scatter(sample_df['avg'],sample_df['strike_rate']) # this is only sccaters plot of batsman
for i in range (sample_df.shape[0]):
    plt.text(sample_df['avg'].values[i],sample_df['strike_rate'].values[i],sample_df['batter'].values[i])

